### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by bogeeee** [Opire/docs#11]
Section 2: Set up the organization's Stripe account

is too much read and wondering why, for that you're not that big yet that this is of a concern now.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it means? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #11</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @bogeeee</code> (replace <code>20</code> with the amount, and <code>@bogeeee</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by RubenRuCh** [comment]
Thanks a lot for your feedback! 

We reviewed it, and you're right - it was too much text. Also, we were almost forcing code owners to set up a Stripe account at the beginning, and that could make a lot of people reticent to start using Opire.

We reduced the text and also mark the step as `Optional`, hope now it's more readable.

https://docs.opire.dev/overview/getting-started
