### ISSUE TITLE
Add French as a supported language

### ISSUE THREAD

**Issue by RubenRuCh** [Opire/docs#2]
We've built our documentation using [Nextra](https://nextra.site/docs). Right now, only Spanish and English are supported, but we would like to support more languages. 

This issue is for adding support for French.

## How to add support for a new language

The project is structured following [Nextra documentation](https://nextra.site/docs/docs-theme/start). There are a lot of files that have several versions of the same file (e.g. `introduction.en.mdx` and `introduction.es.mdx`). To add a new language, create a new version of every file (e.g. `introduction.fr.mdx`) and translate the content of the file using the English version as the base.

### Requirements
- The language name for French should be `fr`
- Include the new language in `locales` inside `next.config.js`
- All files must be translated (including `FAQ`)
- Spelling errors will not be accepted
- We prefer effective communication over a literal translation. Some concepts may be better to leave in English if the French translation doesn't make much sense in Opire's context

**Comment by TronSkywalker** [comment]
Can I have this one issue assigned? will submit PR by Sunday :)
Want to try out the reward system

(I am half french 🇫🇷  )

**Comment by RubenRuCh** [comment]
Thanks @TronSkywalker!

Remember to [claim](https://docs.opire.dev/overview/commands#claim-rewards-associated-with-an-issue) the reward once you make the PR, so I get notified

**Comment by ivanfernandez2646** [comment]
Hi, @TronSkywalker are you working on this??

If you leave or reject the task for any reason, please let me know and I'll try to do it.

Many thanks!!

**Comment by TronSkywalker** [comment]
yeah take it.. didnt find the time sry xD

**Comment by ivanfernandez2646** [comment]
Hi, @RubenRuCh. I closed the first PR by a little mistake. The new PR is #10
